/**
 * Programme constants.
 *
 * The state and zone lists are the real administrative geography of Nigeria and
 * match `public/geo/*.geojson` after slugification. Nothing here is a finding —
 * findings live in `public/data`, and every one of them is synthetic.
 */

import { NATIONAL_TOTAL } from './nationalSplit';
import type { EvidenceGrade } from './types';

export const PROGRAMME = {
  title: 'EMR Readiness Assessment',
  subtitle:
    'Readiness findings across 36 states, 305 LGAs, and 2,804 healthcare facilities',
  partners: ['NPHCDA', 'NTBLCP', 'The Global Fund', 'Solina'],
} as const;

/**
 * Programme coverage.
 *
 * The geography is carried over from the real assessment unchanged — 36 states
 * plus the FCT, 305 LGAs across the 12 primary states, ~2,800 facilities — so
 * the maps, the zone splits and the state lists are all real. Only the
 * *findings* attached to them are synthetic.
 */
export const COVERAGE = {
  statesTotal: 37, // 36 + FCT
  statesPrimary: 12,
  statesSecondary: 25, // + FCT
  /** Every LGA in the 12 primary states — the assessment reached all of them. */
  lgas: 305,
  /**
   * Facilities in the generated population.
   *
   * Read from the generated module rather than written here, so the figure on
   * the landing page cannot drift from the dataset behind it — the generator is
   * the only thing that decides how many facilities exist.
   */
  facilitiesScored: NATIONAL_TOTAL,
} as const;

/**
 * The 12 states with primary facility data collection.
 *
 * Everywhere else in Nigeria was covered by secondary desk review, which yields
 * state-level findings only. The distinction is load-bearing: a user comparing
 * Kano (444 facilities assessed) with a desk-reviewed state is comparing two
 * different kinds of claim, and the UI has to say so.
 */
export const PRIMARY_STATES = [
  'Adamawa',
  'Akwa Ibom',
  'Anambra',
  'Bauchi',
  'Imo',
  'Jigawa',
  'Kano',
  'Lagos',
  'Nasarawa',
  'Niger',
  'Oyo',
  'Rivers',
] as const;

export type PrimaryState = (typeof PRIMARY_STATES)[number];

/** Facilities per primary state — the real sample sizes, reused so the
 *  synthetic population is distributed the way the assessment actually was. */
export const PRIMARY_STATE_FACILITY_COUNTS: Record<PrimaryState, number> = {
  Kano: 444,
  Anambra: 282,
  Jigawa: 267,
  Niger: 257,
  Oyo: 257,
  'Akwa Ibom': 250,
  Imo: 229,
  Adamawa: 201,
  Bauchi: 181,
  Lagos: 159,
  Nasarawa: 152,
  Rivers: 146,
};

export const ALL_STATES = [
  'Abia', 'Adamawa', 'Akwa Ibom', 'Anambra', 'Bauchi', 'Bayelsa', 'Benue',
  'Borno', 'Cross River', 'Delta', 'Ebonyi', 'Edo', 'Ekiti', 'Enugu', 'FCT',
  'Gombe', 'Imo', 'Jigawa', 'Kaduna', 'Kano', 'Katsina', 'Kebbi', 'Kogi',
  'Kwara', 'Lagos', 'Nasarawa', 'Niger', 'Ogun', 'Ondo', 'Osun', 'Oyo',
  'Plateau', 'Rivers', 'Sokoto', 'Taraba', 'Yobe', 'Zamfara',
] as const;

export const ZONES = [
  'north_central',
  'north_east',
  'north_west',
  'south_east',
  'south_south',
  'south_west',
] as const;

export const ZONE_LABELS: Record<(typeof ZONES)[number], string> = {
  north_central: 'North Central',
  north_east: 'North East',
  north_west: 'North West',
  south_east: 'South East',
  south_south: 'South South',
  south_west: 'South West',
};

export function evidenceGrade(state: string): EvidenceGrade {
  return (PRIMARY_STATES as readonly string[]).includes(state)
    ? 'primary'
    : 'secondary';
}

export const FUNCTIONALITY_LEVELS = [
  'Functional L1',
  'Functional L2',
  'Partially Functional',
] as const;

export const SERVICE_POINTS = [
  { id: 'registration', label: 'Registration' },
  { id: 'examination', label: 'Examination / triage' },
  { id: 'consultation', label: 'Consultation' },
  { id: 'laboratory', label: 'Laboratory' },
  { id: 'pharmacy', label: 'Pharmacy' },
] as const;

// ---------------------------------------------------------------------------
// Data paths
// ---------------------------------------------------------------------------

export const CURRENCY = { code: 'NGN', symbol: '₦', locale: 'en-NG' } as const;

/**
 * Everything under `/data` is synthetic — generated by
 * `npm run data:generate`, committed, and served statically. There is no ETL
 * and no source workbook in this repository. See docs/DUMMY_DATA.md.
 */
export const DATA_PATHS = {
  snapshot: '/data/snapshot.json',
  facilitiesSummary: '/data/facilities-summary.json',
  states: '/data/states.json',
  lgas: '/data/lgas.json',
  national: '/data/national.json',
  statesGeo: '/geo/nigeria-states.geojson',
  lgasGeo: '/geo/nigeria-lgas.geojson',
} as const;
