/**
 * GENERATED by scripts/ingest-assessment.mjs — do not edit.
 *
 * The gap dictionary, extracted from the assessment dataset rather than
 * declared. Three levels, as the source has them: **domain → gap area →
 * condition**. Every entry in `GAPS` is a condition the survey actually
 * recorded, sitting in one of the twenty areas and carrying the interventions
 * it triggers at the urgency and price the sheet gives them.
 *
 * Emitted rather than fetched: every control that offers a gap needs the whole
 * list before it can render one, so a network round-trip would only buy a
 * spinner on a filter dropdown.
 *
 * There is no leadership & governance domain — it is not assessed at facility
 * level and has no column in the source.
 */

import type {
  Band,
  FacilityThemeId,
  GapAreaId,
  GapDomainId,
  GapSeverity,
  Horizon,
} from './types';

/** Urgencies, worst-first. The source's own four, not a three-level
 *  approximation of them: major and critical are exactly what the deployment
 *  band is computed from. */
export const HORIZONS: Horizon[] = ["critical","major","minor","long_term"];

export const HORIZON_LABEL: Record<Horizon, string> = {
  critical: "Critical — before deployment",
  major: "Major — before deployment",
  minor: "Minor — during deployment",
  long_term: "Optional — after deployment",
};

/** The short form, for a chip beside a gap. */
export const HORIZON_SHORT: Record<Horizon, string> = {
  critical: "Critical",
  major: "Major",
  minor: "Minor",
  long_term: "Optional",
};

/** What an intervention's urgency does to its domain's band. */
export const HORIZON_SEVERITY: Record<Horizon, GapSeverity> = {
  critical: "blocking",
  major: "blocking",
  minor: "partial",
  long_term: "partial",
};

export const GAP_DOMAINS = [
  {
    "id": "technical_infrastructure",
    "label": "Technical Infrastructure",
    "costed": true
  },
  {
    "id": "workforce_capacity",
    "label": "Workforce Capacity",
    "costed": true
  },
  {
    "id": "workflow_transition",
    "label": "Workflow & Transition",
    "costed": true
  },
  {
    "id": "data_use_reporting",
    "label": "Data Use & Reporting",
    "costed": true
  }
] as const;

export const GAP_DOMAIN_LABEL: Record<GapDomainId, string> = {
  "technical_infrastructure": "Technical Infrastructure",
  "workforce_capacity": "Workforce Capacity",
  "workflow_transition": "Workflow & Transition",
  "data_use_reporting": "Data Use & Reporting"
};

export interface GapInterventionDef {
  id: string;
  label: string;
  horizon: Horizon;
  /** Null where the source carries no price. Not zero — see
   *  docs/data-queries/README.md, Query B. */
  costNGN: number | null;
}

export interface GapAreaDef {
  id: GapAreaId;
  domain: GapDomainId;
  /** The column header without its trailing "gap" — "Power",
   *  "Facility-connectivity". Say "Power gap" where the noun is wanted. */
  label: string;
  /** Position in the sheet, which leads each domain with its blocking areas. */
  order: number;
}

/**
 * The gap areas — the level between a domain and a gap.
 *
 * Twenty of them, one per gap column in the source. A facility holds **at most
 * one condition per area**, because a column holds one value, and that is what
 * makes the area the unit a filter and a rollup can count: counting areas
 * counts facilities, where counting conditions counts survey answers.
 *
 * In the sheet's column order, not alphabetical — see `extractGapAreas`.
 */
export const GAP_AREAS: GapAreaDef[] = [
  {
    "id": "power",
    "domain": "technical_infrastructure",
    "label": "Power",
    "order": 0
  },
  {
    "id": "wiring",
    "domain": "technical_infrastructure",
    "label": "Wiring",
    "order": 1
  },
  {
    "id": "facility_connectivity",
    "domain": "technical_infrastructure",
    "label": "Facility-connectivity",
    "order": 2
  },
  {
    "id": "device_sufficiency",
    "domain": "technical_infrastructure",
    "label": "Device-sufficiency",
    "order": 3
  },
  {
    "id": "backup_power",
    "domain": "technical_infrastructure",
    "label": "Backup-power",
    "order": 4
  },
  {
    "id": "backup_connectivity",
    "domain": "technical_infrastructure",
    "label": "Backup-connectivity",
    "order": 5
  },
  {
    "id": "device_maintenance",
    "domain": "technical_infrastructure",
    "label": "Device-maintenance",
    "order": 6
  },
  {
    "id": "data_backup",
    "domain": "technical_infrastructure",
    "label": "Data-backup",
    "order": 7
  },
  {
    "id": "mobile_network_feasibility",
    "domain": "technical_infrastructure",
    "label": "Mobile-network feasibility",
    "order": 8
  },
  {
    "id": "digital_competency",
    "domain": "workforce_capacity",
    "label": "Digital-competency",
    "order": 9
  },
  {
    "id": "emr_data_focal_person",
    "domain": "workforce_capacity",
    "label": "EMR/Data focal-person",
    "order": 10
  },
  {
    "id": "training",
    "domain": "workforce_capacity",
    "label": "Training",
    "order": 11
  },
  {
    "id": "technical_support",
    "domain": "workforce_capacity",
    "label": "Technical-support",
    "order": 12
  },
  {
    "id": "duplicate_entry",
    "domain": "workflow_transition",
    "label": "Duplicate-entry",
    "order": 13
  },
  {
    "id": "workflow_bottleneck",
    "domain": "workflow_transition",
    "label": "Workflow-bottleneck",
    "order": 14
  },
  {
    "id": "physical_service_point",
    "domain": "workflow_transition",
    "label": "Physical service-point",
    "order": 15
  },
  {
    "id": "staff_willingness_support",
    "domain": "workflow_transition",
    "label": "Staff-willingness support",
    "order": 16
  },
  {
    "id": "routine_data_use",
    "domain": "data_use_reporting",
    "label": "Routine-data-use",
    "order": 17
  },
  {
    "id": "data_validation",
    "domain": "data_use_reporting",
    "label": "Data-validation",
    "order": 18
  },
  {
    "id": "report_review_support",
    "domain": "data_use_reporting",
    "label": "Report-review support",
    "order": 19
  }
];

export const GAP_AREA_BY_ID: Record<string, GapAreaDef> = Object.fromEntries(
  GAP_AREAS.map((a) => [a.id, a]),
);

/** Gap areas for a domain selection. No domains ticked means every area — the
 *  same grammar as LGA under State. */
export function gapAreasForDomains(domains: readonly string[]): GapAreaDef[] {
  if (!domains.length) return GAP_AREAS;
  return GAP_AREAS.filter((a) => domains.includes(a.domain));
}

export interface GapDef {
  id: string;
  domain: GapDomainId;
  /** The gap area this condition sits in. An id — the label is on
   *  `GAP_AREA_BY_ID`, so nothing renders a sliced column header. */
  area: GapAreaId;
  /** The condition the survey recorded, verbatim. */
  label: string;
  severity: GapSeverity;
  interventions: GapInterventionDef[];
}

export const GAPS: GapDef[] = [
  {
    "id": "power__no_functional_electricity_source_or_0_hours_day",
    "domain": "technical_infrastructure",
    "area": "power",
    "label": "No functional electricity source or 0 hours/day",
    "severity": "blocking",
    "interventions": [
      {
        "id": "install_solar_panels_and_batteries__be5a79",
        "label": "Install solar panels and batteries that can power the EMR equipment.",
        "horizon": "critical",
        "costNGN": 3000000
      },
      {
        "id": "connect_the_facility_to_the__1563cf",
        "label": "Connect the facility to the electricity grid.",
        "horizon": "long_term",
        "costNGN": 500000
      }
    ]
  },
  {
    "id": "power__best_usable_source_provides_1_4_hours_day",
    "domain": "technical_infrastructure",
    "area": "power",
    "label": "Best usable source provides 1–4 hours/day",
    "severity": "blocking",
    "interventions": [
      {
        "id": "add_solar_panels_or_batteries__8a2263",
        "label": "Add solar panels or batteries so EMR equipment has power for at least nine hours.",
        "horizon": "minor",
        "costNGN": 1200000
      },
      {
        "id": "install_solar_panels_and_batteries__cd156c",
        "label": "Install solar panels and batteries that can power the EMR equipment.",
        "horizon": "major",
        "costNGN": 3000000
      }
    ]
  },
  {
    "id": "power__best_usable_source_provides_5_8_hours_day",
    "domain": "technical_infrastructure",
    "area": "power",
    "label": "Best usable source provides 5–8 hours/day",
    "severity": "blocking",
    "interventions": [
      {
        "id": "add_solar_panels_or_batteries__8a2263",
        "label": "Add solar panels or batteries so EMR equipment has power for at least nine hours.",
        "horizon": "minor",
        "costNGN": 1200000
      },
      {
        "id": "install_solar_panels_and_batteries__cd156c",
        "label": "Install solar panels and batteries that can power the EMR equipment.",
        "horizon": "major",
        "costNGN": 3000000
      }
    ]
  },
  {
    "id": "wiring__no_functional_wiring_or_wiring_condition_not_demonstrate",
    "domain": "technical_infrastructure",
    "area": "wiring",
    "label": "No functional wiring or wiring condition not demonstrated",
    "severity": "partial",
    "interventions": [
      {
        "id": "fix_unsafe_wiring_and_add__76bcf2",
        "label": "Fix unsafe wiring and add working wall sockets where EMR equipment will be used.",
        "horizon": "minor",
        "costNGN": 388000
      }
    ]
  },
  {
    "id": "wiring__partially_functional_unreliable_or_inadequate_wiring",
    "domain": "technical_infrastructure",
    "area": "wiring",
    "label": "Partially functional, unreliable or inadequate wiring",
    "severity": "partial",
    "interventions": [
      {
        "id": "fix_unsafe_wiring_and_add__76bcf2",
        "label": "Fix unsafe wiring and add working wall sockets where EMR equipment will be used.",
        "horizon": "minor",
        "costNGN": 388000
      }
    ]
  },
  {
    "id": "facility_connectivity__confirmed_satellite_only_route",
    "domain": "technical_infrastructure",
    "area": "facility_connectivity",
    "label": "Confirmed satellite-only route",
    "severity": "blocking",
    "interventions": [
      {
        "id": "install_satellite_internet_at_the__8c8084",
        "label": "Install satellite internet at the facility after confirming that no land or mobile connection works.",
        "horizon": "critical",
        "costNGN": 3000000
      }
    ]
  },
  {
    "id": "facility_connectivity__no_internet_access_or_network_coverage",
    "domain": "technical_infrastructure",
    "area": "facility_connectivity",
    "label": "No internet access or network coverage",
    "severity": "blocking",
    "interventions": [
      {
        "id": "check_which_connection_works_at__89cff8",
        "label": "Check which connection works at the facility, then use one: FibreX, managed mobile internet, fixed radio, satellite or network extension.",
        "horizon": "critical",
        "costNGN": null
      }
    ]
  },
  {
    "id": "facility_connectivity__facility_managed_connection_speed_not_measured",
    "domain": "technical_infrastructure",
    "area": "facility_connectivity",
    "label": "Facility-managed connection — speed not measured",
    "severity": "partial",
    "interventions": [
      {
        "id": "set_up_internet_fast_enough__9c72b6",
        "label": "Set up internet fast enough to use the EMR: at least 5 Mbps, using FibreX, managed mobile internet or fixed radio.",
        "horizon": "minor",
        "costNGN": 360000
      }
    ]
  },
  {
    "id": "facility_connectivity__facility_managed_connection_at_or_above_5_mbps_with_disr",
    "domain": "technical_infrastructure",
    "area": "facility_connectivity",
    "label": "Facility-managed connection at or above 5 Mbps with disruption",
    "severity": "partial",
    "interventions": [
      {
        "id": "give_the_facility_a_dedicated__77de51",
        "label": "Give the facility a dedicated backup SIM and router so EMR use can continue when the primary connection is disrupted.",
        "horizon": "minor",
        "costNGN": 52000
      }
    ]
  },
  {
    "id": "facility_connectivity__facility_managed_connection_below_5_mbps",
    "domain": "technical_infrastructure",
    "area": "facility_connectivity",
    "label": "Facility-managed connection below 5 Mbps",
    "severity": "partial",
    "interventions": [
      {
        "id": "set_up_internet_fast_enough__9c72b6",
        "label": "Set up internet fast enough to use the EMR: at least 5 Mbps, using FibreX, managed mobile internet or fixed radio.",
        "horizon": "minor",
        "costNGN": 360000
      }
    ]
  },
  {
    "id": "facility_connectivity__individual_connection_speed_not_measured",
    "domain": "technical_infrastructure",
    "area": "facility_connectivity",
    "label": "Individual connection — speed not measured",
    "severity": "partial",
    "interventions": [
      {
        "id": "set_up_internet_fast_enough__9c72b6",
        "label": "Set up internet fast enough to use the EMR: at least 5 Mbps, using FibreX, managed mobile internet or fixed radio.",
        "horizon": "minor",
        "costNGN": 360000
      }
    ]
  },
  {
    "id": "facility_connectivity__individual_connection_at_or_above_5_mbps",
    "domain": "technical_infrastructure",
    "area": "facility_connectivity",
    "label": "Individual connection at or above 5 Mbps",
    "severity": "partial",
    "interventions": [
      {
        "id": "move_the_existing_internet_account__3f59fd",
        "label": "Move the existing internet account into the facility's name and connect it to an EMR router.",
        "horizon": "minor",
        "costNGN": 40000
      }
    ]
  },
  {
    "id": "facility_connectivity__individual_connection_below_5_mbps",
    "domain": "technical_infrastructure",
    "area": "facility_connectivity",
    "label": "Individual connection below 5 Mbps",
    "severity": "partial",
    "interventions": [
      {
        "id": "set_up_internet_fast_enough__9c72b6",
        "label": "Set up internet fast enough to use the EMR: at least 5 Mbps, using FibreX, managed mobile internet or fixed radio.",
        "horizon": "minor",
        "costNGN": 360000
      }
    ]
  },
  {
    "id": "facility_connectivity__facility_managed_connection_at_or_above_5_mbps_and_consi",
    "domain": "technical_infrastructure",
    "area": "facility_connectivity",
    "label": "Facility-managed connection at or above 5 Mbps and consistently reliable",
    "severity": "partial",
    "interventions": []
  },
  {
    "id": "device_sufficiency__all_supported_devices_are_obsolete",
    "domain": "technical_infrastructure",
    "area": "device_sufficiency",
    "label": "All supported devices are obsolete",
    "severity": "partial",
    "interventions": [
      {
        "id": "give_each_place_where_staff__eadb7e",
        "label": "Give each place where staff enter EMR data the number of tablets it is missing.",
        "horizon": "minor",
        "costNGN": 233333
      }
    ]
  },
  {
    "id": "device_sufficiency__immediately_usable_devices_cover_75_99_of_the_minimum_re",
    "domain": "technical_infrastructure",
    "area": "device_sufficiency",
    "label": "Immediately usable devices cover 75%–99% of the minimum requirement",
    "severity": "partial",
    "interventions": [
      {
        "id": "give_each_place_where_staff__eadb7e",
        "label": "Give each place where staff enter EMR data the number of tablets it is missing.",
        "horizon": "minor",
        "costNGN": 233333
      }
    ]
  },
  {
    "id": "device_sufficiency__immediately_usable_devices_cover_less_than_75_of_the_min",
    "domain": "technical_infrastructure",
    "area": "device_sufficiency",
    "label": "Immediately usable devices cover less than 75% of the minimum requirement",
    "severity": "partial",
    "interventions": [
      {
        "id": "give_each_place_where_staff__eadb7e",
        "label": "Give each place where staff enter EMR data the number of tablets it is missing.",
        "horizon": "minor",
        "costNGN": 233333
      }
    ]
  },
  {
    "id": "device_sufficiency__no_supported_computing_devices_are_available",
    "domain": "technical_infrastructure",
    "area": "device_sufficiency",
    "label": "No supported computing devices are available",
    "severity": "partial",
    "interventions": [
      {
        "id": "give_the_facility_three_tablets__0bd7bc",
        "label": "Give the facility three tablets that can run the EMR.",
        "horizon": "minor",
        "costNGN": 700000
      }
    ]
  },
  {
    "id": "device_sufficiency__supported_devices_exist_but_none_is_immediately_deployab",
    "domain": "technical_infrastructure",
    "area": "device_sufficiency",
    "label": "Supported devices exist but none is immediately deployable",
    "severity": "partial",
    "interventions": [
      {
        "id": "give_each_place_where_staff__eadb7e",
        "label": "Give each place where staff enter EMR data the number of tablets it is missing.",
        "horizon": "minor",
        "costNGN": 233333
      }
    ]
  },
  {
    "id": "backup_power__backup_exists_but_is_non_functional",
    "domain": "technical_infrastructure",
    "area": "backup_power",
    "label": "Backup exists but is non-functional",
    "severity": "partial",
    "interventions": [
      {
        "id": "fix_the_backup_power_source__49a29a",
        "label": "Fix the backup power source, or add another backup power source.",
        "horizon": "minor",
        "costNGN": 380000
      }
    ]
  },
  {
    "id": "backup_power__grid_and_functional_backup_are_available_but_backup_runt",
    "domain": "technical_infrastructure",
    "area": "backup_power",
    "label": "Grid and functional backup are available, but backup runtime is below 9 hours",
    "severity": "partial",
    "interventions": [
      {
        "id": "add_solar_panels_or_batteries__e444bb",
        "label": "Add solar panels or batteries so backup power lasts at least nine hours.",
        "horizon": "minor",
        "costNGN": 1200000
      }
    ]
  },
  {
    "id": "backup_power__no_secondary_or_backup_power_pathway",
    "domain": "technical_infrastructure",
    "area": "backup_power",
    "label": "No secondary or backup power pathway",
    "severity": "partial",
    "interventions": [
      {
        "id": "fix_the_backup_power_source__49a29a",
        "label": "Fix the backup power source, or add another backup power source.",
        "horizon": "minor",
        "costNGN": 380000
      }
    ]
  },
  {
    "id": "backup_power__only_one_usable_pathway_or_backup_is_partially_functiona",
    "domain": "technical_infrastructure",
    "area": "backup_power",
    "label": "Only one usable pathway or backup is partially functional",
    "severity": "partial",
    "interventions": [
      {
        "id": "fix_the_backup_power_source__49a29a",
        "label": "Fix the backup power source, or add another backup power source.",
        "horizon": "minor",
        "costNGN": 380000
      }
    ]
  },
  {
    "id": "backup_power__only_one_usable_power_pathway_is_confirmed",
    "domain": "technical_infrastructure",
    "area": "backup_power",
    "label": "Only one usable power pathway is confirmed",
    "severity": "partial",
    "interventions": [
      {
        "id": "fix_the_backup_power_source__49a29a",
        "label": "Fix the backup power source, or add another backup power source.",
        "horizon": "minor",
        "costNGN": 380000
      }
    ]
  },
  {
    "id": "backup_connectivity__backup_reported_but_method_is_unclear_or_unusable",
    "domain": "technical_infrastructure",
    "area": "backup_connectivity",
    "label": "Backup reported, but method is unclear or unusable",
    "severity": "partial",
    "interventions": [
      {
        "id": "give_the_facility_a_data__9931f0",
        "label": "Give the facility a data SIM and router to use when the main internet fails.",
        "horizon": "minor",
        "costNGN": 52000
      }
    ]
  },
  {
    "id": "backup_connectivity__no_backup_internet_option_confirmed",
    "domain": "technical_infrastructure",
    "area": "backup_connectivity",
    "label": "No backup internet option confirmed",
    "severity": "partial",
    "interventions": [
      {
        "id": "give_the_facility_a_data__9931f0",
        "label": "Give the facility a data SIM and router to use when the main internet fails.",
        "horizon": "minor",
        "costNGN": 52000
      }
    ]
  },
  {
    "id": "backup_connectivity__personal_hotspot_or_usb_backup_option",
    "domain": "technical_infrastructure",
    "area": "backup_connectivity",
    "label": "Personal hotspot or USB backup option",
    "severity": "partial",
    "interventions": [
      {
        "id": "give_the_facility_a_data__9931f0",
        "label": "Give the facility a data SIM and router to use when the main internet fails.",
        "horizon": "minor",
        "costNGN": 52000
      }
    ]
  },
  {
    "id": "device_maintenance__formal_annual_maintenance",
    "domain": "technical_infrastructure",
    "area": "device_maintenance",
    "label": "Formal annual maintenance",
    "severity": "partial",
    "interventions": [
      {
        "id": "make_a_monthly_list_of__50cb85",
        "label": "Make a monthly list of device checks. Write down who will fix a broken device and how soon they must fix it.",
        "horizon": "minor",
        "costNGN": 90000
      }
    ]
  },
  {
    "id": "device_maintenance__formal_quarterly_maintenance",
    "domain": "technical_infrastructure",
    "area": "device_maintenance",
    "label": "Formal quarterly maintenance",
    "severity": "partial",
    "interventions": [
      {
        "id": "make_a_monthly_list_of__50cb85",
        "label": "Make a monthly list of device checks. Write down who will fix a broken device and how soon they must fix it.",
        "horizon": "minor",
        "costNGN": 90000
      }
    ]
  },
  {
    "id": "device_maintenance__maintenance_only_when_devices_fail_or_as_needed",
    "domain": "technical_infrastructure",
    "area": "device_maintenance",
    "label": "Maintenance only when devices fail or as needed",
    "severity": "partial",
    "interventions": [
      {
        "id": "make_a_monthly_list_of__50cb85",
        "label": "Make a monthly list of device checks. Write down who will fix a broken device and how soon they must fix it.",
        "horizon": "minor",
        "costNGN": 90000
      }
    ]
  },
  {
    "id": "device_maintenance__no_formal_maintenance_arrangement",
    "domain": "technical_infrastructure",
    "area": "device_maintenance",
    "label": "No formal maintenance arrangement",
    "severity": "partial",
    "interventions": [
      {
        "id": "make_a_monthly_list_of__50cb85",
        "label": "Make a monthly list of device checks. Write down who will fix a broken device and how soon they must fix it.",
        "horizon": "minor",
        "costNGN": 90000
      }
    ]
  },
  {
    "id": "device_maintenance__no_maintenance_schedule_reported",
    "domain": "technical_infrastructure",
    "area": "device_maintenance",
    "label": "No maintenance schedule reported",
    "severity": "partial",
    "interventions": [
      {
        "id": "make_a_monthly_list_of__50cb85",
        "label": "Make a monthly list of device checks. Write down who will fix a broken device and how soon they must fix it.",
        "horizon": "minor",
        "costNGN": 90000
      }
    ]
  },
  {
    "id": "data_backup__manual_data_backup_capability",
    "domain": "technical_infrastructure",
    "area": "data_backup",
    "label": "Manual data-backup capability",
    "severity": "partial",
    "interventions": [
      {
        "id": "set_the_emr_to_copy__a92660",
        "label": "Set the EMR to copy its data every day. Test that the data can be brought back. Name the person who checks this.",
        "horizon": "minor",
        "costNGN": 60000
      }
    ]
  },
  {
    "id": "data_backup__no_data_backup_capability_reported",
    "domain": "technical_infrastructure",
    "area": "data_backup",
    "label": "No data-backup capability reported",
    "severity": "partial",
    "interventions": [
      {
        "id": "set_the_emr_to_copy__a92660",
        "label": "Set the EMR to copy its data every day. Test that the data can be brought back. Name the person who checks this.",
        "horizon": "minor",
        "costNGN": 60000
      }
    ]
  },
  {
    "id": "mobile_network_feasibility__no_serviceable_mobile_pathway",
    "domain": "technical_infrastructure",
    "area": "mobile_network_feasibility",
    "label": "No serviceable mobile pathway",
    "severity": "blocking",
    "interventions": [
      {
        "id": "install_satellite_internet_at_the__8c8084",
        "label": "Install satellite internet at the facility after confirming that no land or mobile connection works.",
        "horizon": "critical",
        "costNGN": 3000000
      }
    ]
  },
  {
    "id": "mobile_network_feasibility__network_extension_required",
    "domain": "technical_infrastructure",
    "area": "mobile_network_feasibility",
    "label": "Network extension required",
    "severity": "blocking",
    "interventions": [
      {
        "id": "work_with_the_provider_to__eaff3c",
        "label": "Work with the provider to extend the network to the facility and install a facility-managed connection.",
        "horizon": "major",
        "costNGN": 750000
      }
    ]
  },
  {
    "id": "digital_competency__50_74_of_applicable_service_points_have_basic_digital_sk",
    "domain": "workforce_capacity",
    "area": "digital_competency",
    "label": "50–74% of applicable service points have basic digital skills",
    "severity": "partial",
    "interventions": [
      {
        "id": "train_every_person_who_will__186e9d",
        "label": "Train every person who will use the EMR. Stay with them while they first use it. Train new staff and repeat training every three months.",
        "horizon": "minor",
        "costNGN": 30000
      }
    ]
  },
  {
    "id": "digital_competency__75_99_of_applicable_service_points_have_basic_digital_sk",
    "domain": "workforce_capacity",
    "area": "digital_competency",
    "label": "75–99% of applicable service points have basic digital skills",
    "severity": "partial",
    "interventions": [
      {
        "id": "train_every_person_who_will__186e9d",
        "label": "Train every person who will use the EMR. Stay with them while they first use it. Train new staff and repeat training every three months.",
        "horizon": "minor",
        "costNGN": 30000
      }
    ]
  },
  {
    "id": "digital_competency__less_than_50_of_applicable_service_points_have_basic_dig",
    "domain": "workforce_capacity",
    "area": "digital_competency",
    "label": "Less than 50% of applicable service points have basic digital skills",
    "severity": "partial",
    "interventions": [
      {
        "id": "train_every_person_who_will__186e9d",
        "label": "Train every person who will use the EMR. Stay with them while they first use it. Train new staff and repeat training every three months.",
        "horizon": "minor",
        "costNGN": 30000
      }
    ]
  },
  {
    "id": "digital_competency__no_applicable_service_point_has_basic_digital_skills",
    "domain": "workforce_capacity",
    "area": "digital_competency",
    "label": "No applicable service point has basic digital skills",
    "severity": "partial",
    "interventions": [
      {
        "id": "train_every_person_who_will__186e9d",
        "label": "Train every person who will use the EMR. Stay with them while they first use it. Train new staff and repeat training every three months.",
        "horizon": "minor",
        "costNGN": 30000
      }
    ]
  },
  {
    "id": "emr_data_focal_person__dedicated_hro_m_e_officer_part_time_shared",
    "domain": "workforce_capacity",
    "area": "emr_data_focal_person",
    "label": "Dedicated HRO/M&E officer — part-time/shared",
    "severity": "partial",
    "interventions": [
      {
        "id": "write_down_the_emr_and__2f911d",
        "label": "Write down the EMR and data tasks for the named staff member. Set aside time for the work and name who checks that it is done.",
        "horizon": "minor",
        "costNGN": 0
      }
    ]
  },
  {
    "id": "emr_data_focal_person__no_dedicated_hro_m_e_officer",
    "domain": "workforce_capacity",
    "area": "emr_data_focal_person",
    "label": "No dedicated HRO/M&E officer",
    "severity": "partial",
    "interventions": [
      {
        "id": "name_a_staff_member_to__1a4c61",
        "label": "Name a staff member to lead EMR and data work. If there is no HR or data officer, give this job to the person in charge of the facility.",
        "horizon": "minor",
        "costNGN": 0
      }
    ]
  },
  {
    "id": "training__no_formal_digital_health_training",
    "domain": "workforce_capacity",
    "area": "training",
    "label": "No formal digital-health training",
    "severity": "partial",
    "interventions": [
      {
        "id": "train_staff_on_the_emr__65c6ef",
        "label": "Train staff on the EMR tasks they need. Write down who completed training. Train new staff and repeat training every three months.",
        "horizon": "minor",
        "costNGN": 30000
      }
    ]
  },
  {
    "id": "training__training_6_12_months_ago_and_foundational",
    "domain": "workforce_capacity",
    "area": "training",
    "label": "Training 6–12 months ago and foundational",
    "severity": "partial",
    "interventions": [
      {
        "id": "train_staff_on_the_emr__65c6ef",
        "label": "Train staff on the EMR tasks they need. Write down who completed training. Train new staff and repeat training every three months.",
        "horizon": "minor",
        "costNGN": 30000
      }
    ]
  },
  {
    "id": "training__training_6_12_months_ago_with_low_relevance",
    "domain": "workforce_capacity",
    "area": "training",
    "label": "Training 6–12 months ago with low relevance",
    "severity": "partial",
    "interventions": [
      {
        "id": "train_staff_on_the_emr__65c6ef",
        "label": "Train staff on the EMR tasks they need. Write down who completed training. Train new staff and repeat training every three months.",
        "horizon": "minor",
        "costNGN": 30000
      }
    ]
  },
  {
    "id": "training__training_over_1_year_ago_and_directly_relevant",
    "domain": "workforce_capacity",
    "area": "training",
    "label": "Training over 1 year ago and directly relevant",
    "severity": "partial",
    "interventions": [
      {
        "id": "train_staff_on_the_emr__65c6ef",
        "label": "Train staff on the EMR tasks they need. Write down who completed training. Train new staff and repeat training every three months.",
        "horizon": "minor",
        "costNGN": 30000
      }
    ]
  },
  {
    "id": "training__training_over_1_year_ago_with_foundational_or_low_releva",
    "domain": "workforce_capacity",
    "area": "training",
    "label": "Training over 1 year ago with foundational or low relevance",
    "severity": "partial",
    "interventions": [
      {
        "id": "train_staff_on_the_emr__65c6ef",
        "label": "Train staff on the EMR tasks they need. Write down who completed training. Train new staff and repeat training every three months.",
        "horizon": "minor",
        "costNGN": 30000
      }
    ]
  },
  {
    "id": "training__training_within_6_months_and_foundational",
    "domain": "workforce_capacity",
    "area": "training",
    "label": "Training within 6 months and foundational",
    "severity": "partial",
    "interventions": [
      {
        "id": "train_staff_on_the_emr__65c6ef",
        "label": "Train staff on the EMR tasks they need. Write down who completed training. Train new staff and repeat training every three months.",
        "horizon": "minor",
        "costNGN": 30000
      }
    ]
  },
  {
    "id": "training__training_within_6_months_with_low_relevance",
    "domain": "workforce_capacity",
    "area": "training",
    "label": "Training within 6 months with low relevance",
    "severity": "partial",
    "interventions": [
      {
        "id": "train_staff_on_the_emr__65c6ef",
        "label": "Train staff on the EMR tasks they need. Write down who completed training. Train new staff and repeat training every three months.",
        "horizon": "minor",
        "costNGN": 30000
      }
    ]
  },
  {
    "id": "technical_support__issues_are_resolved_within_24_hours_through_an_informal",
    "domain": "workforce_capacity",
    "area": "technical_support",
    "label": "Issues are resolved within 24 hours through an informal or external pathway",
    "severity": "partial",
    "interventions": [
      {
        "id": "make_a_state_support_list__a8f3d2",
        "label": "Make a state support list: who receives EMR problems, who fixes them and the date they must reply.",
        "horizon": "minor",
        "costNGN": 1200000
      }
    ]
  },
  {
    "id": "technical_support__issues_are_usually_resolved_within_24_48_hours",
    "domain": "workforce_capacity",
    "area": "technical_support",
    "label": "Issues are usually resolved within 24–48 hours",
    "severity": "partial",
    "interventions": [
      {
        "id": "make_a_state_support_list__a8f3d2",
        "label": "Make a state support list: who receives EMR problems, who fixes them and the date they must reply.",
        "horizon": "minor",
        "costNGN": 1200000
      }
    ]
  },
  {
    "id": "technical_support__issues_usually_take_more_than_48_hours_to_resolve",
    "domain": "workforce_capacity",
    "area": "technical_support",
    "label": "Issues usually take more than 48 hours to resolve",
    "severity": "partial",
    "interventions": [
      {
        "id": "make_a_state_support_list__a8f3d2",
        "label": "Make a state support list: who receives EMR problems, who fixes them and the date they must reply.",
        "horizon": "minor",
        "costNGN": 1200000
      }
    ]
  },
  {
    "id": "technical_support__no_defined_technical_support_process",
    "domain": "workforce_capacity",
    "area": "technical_support",
    "label": "No defined technical-support process",
    "severity": "partial",
    "interventions": [
      {
        "id": "make_a_state_support_list__a8f3d2",
        "label": "Make a state support list: who receives EMR problems, who fixes them and the date they must reply.",
        "horizon": "minor",
        "costNGN": 1200000
      }
    ]
  },
  {
    "id": "duplicate_entry__25_49_of_documenting_service_points_affected",
    "domain": "workflow_transition",
    "area": "duplicate_entry",
    "label": "25%–49% of documenting service points affected",
    "severity": "partial",
    "interventions": [
      {
        "id": "draw_how_patients_and_forms__90f73e",
        "label": "Draw how patients and forms move at each service point. Write the new EMR steps and the date paper records will stop.",
        "horizon": "minor",
        "costNGN": 75000
      }
    ]
  },
  {
    "id": "duplicate_entry__50_74_of_documenting_service_points_affected",
    "domain": "workflow_transition",
    "area": "duplicate_entry",
    "label": "50%–74% of documenting service points affected",
    "severity": "partial",
    "interventions": [
      {
        "id": "draw_how_patients_and_forms__90f73e",
        "label": "Draw how patients and forms move at each service point. Write the new EMR steps and the date paper records will stop.",
        "horizon": "minor",
        "costNGN": 75000
      }
    ]
  },
  {
    "id": "duplicate_entry__at_least_75_of_documenting_service_points_affected",
    "domain": "workflow_transition",
    "area": "duplicate_entry",
    "label": "At least 75% of documenting service points affected",
    "severity": "partial",
    "interventions": [
      {
        "id": "draw_how_patients_and_forms__90f73e",
        "label": "Draw how patients and forms move at each service point. Write the new EMR steps and the date paper records will stop.",
        "horizon": "minor",
        "costNGN": 75000
      }
    ]
  },
  {
    "id": "workflow_bottleneck__25_49_of_documenting_service_points_affected",
    "domain": "workflow_transition",
    "area": "workflow_bottleneck",
    "label": "25%–49% of documenting service points affected",
    "severity": "partial",
    "interventions": [
      {
        "id": "change_the_emr_steps_user__73e35a",
        "label": "Change the EMR steps, user roles, queues and permissions to remove the delay or repeated step found during review.",
        "horizon": "minor",
        "costNGN": 125000
      }
    ]
  },
  {
    "id": "workflow_bottleneck__50_74_of_documenting_service_points_affected",
    "domain": "workflow_transition",
    "area": "workflow_bottleneck",
    "label": "50%–74% of documenting service points affected",
    "severity": "partial",
    "interventions": [
      {
        "id": "change_the_emr_steps_user__73e35a",
        "label": "Change the EMR steps, user roles, queues and permissions to remove the delay or repeated step found during review.",
        "horizon": "minor",
        "costNGN": 125000
      }
    ]
  },
  {
    "id": "workflow_bottleneck__at_least_75_of_documenting_service_points_affected",
    "domain": "workflow_transition",
    "area": "workflow_bottleneck",
    "label": "At least 75% of documenting service points affected",
    "severity": "partial",
    "interventions": [
      {
        "id": "change_the_emr_steps_user__73e35a",
        "label": "Change the EMR steps, user roles, queues and permissions to remove the delay or repeated step found during review.",
        "horizon": "minor",
        "costNGN": 125000
      }
    ]
  },
  {
    "id": "physical_service_point__0_of_applicable_service_points_meet_all_minimum_conditio",
    "domain": "workflow_transition",
    "area": "physical_service_point",
    "label": "0% of applicable service points meet all minimum conditions",
    "severity": "partial",
    "interventions": [
      {
        "id": "visit_every_service_point_buy__b68091",
        "label": "Visit every service point. Buy any missing desk, chair, socket, fan or lockable door.",
        "horizon": "minor",
        "costNGN": 54378
      }
    ]
  },
  {
    "id": "physical_service_point__1_49_of_applicable_service_points_meet_all_minimum_condi",
    "domain": "workflow_transition",
    "area": "physical_service_point",
    "label": "1%–49% of applicable service points meet all minimum conditions",
    "severity": "partial",
    "interventions": [
      {
        "id": "visit_every_service_point_buy__b68091",
        "label": "Visit every service point. Buy any missing desk, chair, socket, fan or lockable door.",
        "horizon": "minor",
        "costNGN": 54378
      }
    ]
  },
  {
    "id": "physical_service_point__50_74_of_applicable_service_points_meet_all_minimum_cond",
    "domain": "workflow_transition",
    "area": "physical_service_point",
    "label": "50%–74% of applicable service points meet all minimum conditions",
    "severity": "partial",
    "interventions": [
      {
        "id": "visit_every_service_point_buy__b68091",
        "label": "Visit every service point. Buy any missing desk, chair, socket, fan or lockable door.",
        "horizon": "minor",
        "costNGN": 54378
      }
    ]
  },
  {
    "id": "staff_willingness_support__unwilling",
    "domain": "workflow_transition",
    "area": "staff_willingness_support",
    "label": "Unwilling",
    "severity": "partial",
    "interventions": [
      {
        "id": "meet_all_staff_before_the__cb2b7d",
        "label": "Meet all staff before the EMR starts. Explain the change, name staff who can help others, and hold a meeting every month to answer questions and solve problems.",
        "horizon": "minor",
        "costNGN": 50000
      }
    ]
  },
  {
    "id": "staff_willingness_support__very_unwilling",
    "domain": "workflow_transition",
    "area": "staff_willingness_support",
    "label": "Very unwilling",
    "severity": "partial",
    "interventions": [
      {
        "id": "meet_all_staff_before_the__cb2b7d",
        "label": "Meet all staff before the EMR starts. Explain the change, name staff who can help others, and hold a meeting every month to answer questions and solve problems.",
        "horizon": "minor",
        "costNGN": 50000
      }
    ]
  },
  {
    "id": "routine_data_use__data_rarely_used_or_no_structured_mechanism",
    "domain": "data_use_reporting",
    "area": "routine_data_use",
    "label": "Data rarely used or no structured mechanism",
    "severity": "partial",
    "interventions": [
      {
        "id": "hold_a_facility_meeting_every__054da7",
        "label": "Hold a facility meeting every month. Look at EMR data, agree actions, write them down and check they were done.",
        "horizon": "minor",
        "costNGN": 30000
      }
    ]
  },
  {
    "id": "routine_data_use__one_structured_data_use_mechanism",
    "domain": "data_use_reporting",
    "area": "routine_data_use",
    "label": "One structured data-use mechanism",
    "severity": "partial",
    "interventions": [
      {
        "id": "hold_a_facility_meeting_every__054da7",
        "label": "Hold a facility meeting every month. Look at EMR data, agree actions, write them down and check they were done.",
        "horizon": "minor",
        "costNGN": 30000
      }
    ]
  },
  {
    "id": "data_validation__no_validation_meetings",
    "domain": "data_use_reporting",
    "area": "data_validation",
    "label": "No validation meetings",
    "severity": "partial",
    "interventions": [
      {
        "id": "hold_a_data_check_meeting__1114c4",
        "label": "Hold a data-check meeting every month. Compare records, correct errors, write actions and check they were done.",
        "horizon": "minor",
        "costNGN": 30000
      }
    ]
  },
  {
    "id": "data_validation__quarterly_validation_meetings",
    "domain": "data_use_reporting",
    "area": "data_validation",
    "label": "Quarterly validation meetings",
    "severity": "partial",
    "interventions": [
      {
        "id": "hold_a_data_check_meeting__1114c4",
        "label": "Hold a data-check meeting every month. Compare records, correct errors, write actions and check they were done.",
        "horizon": "minor",
        "costNGN": 30000
      }
    ]
  },
  {
    "id": "data_validation__validation_meetings_occur_without_a_structured_schedule",
    "domain": "data_use_reporting",
    "area": "data_validation",
    "label": "Validation meetings occur without a structured schedule",
    "severity": "partial",
    "interventions": [
      {
        "id": "hold_a_data_check_meeting__1114c4",
        "label": "Hold a data-check meeting every month. Compare records, correct errors, write actions and check they were done.",
        "horizon": "minor",
        "costNGN": 30000
      }
    ]
  },
  {
    "id": "report_review_support__reports_are_never_discussed",
    "domain": "data_use_reporting",
    "area": "report_review_support",
    "label": "Reports are never discussed",
    "severity": "partial",
    "interventions": [
      {
        "id": "review_emr_reports_at_the__9e347a",
        "label": "Review EMR reports at the monthly performance meeting. Agree actions, write them down and check they were done.",
        "horizon": "minor",
        "costNGN": 20000
      }
    ]
  },
  {
    "id": "report_review_support__reports_are_rarely_discussed",
    "domain": "data_use_reporting",
    "area": "report_review_support",
    "label": "Reports are rarely discussed",
    "severity": "partial",
    "interventions": [
      {
        "id": "review_emr_reports_at_the__9e347a",
        "label": "Review EMR reports at the monthly performance meeting. Agree actions, write them down and check they were done.",
        "horizon": "minor",
        "costNGN": 20000
      }
    ]
  },
  {
    "id": "report_review_support__reports_are_sometimes_discussed",
    "domain": "data_use_reporting",
    "area": "report_review_support",
    "label": "Reports are sometimes discussed",
    "severity": "partial",
    "interventions": [
      {
        "id": "review_emr_reports_at_the__9e347a",
        "label": "Review EMR reports at the monthly performance meeting. Agree actions, write them down and check they were done.",
        "horizon": "minor",
        "costNGN": 20000
      }
    ]
  },
  {
    "id": "report_review_support__reports_never_discussed_because_no_validation_meeting_oc",
    "domain": "data_use_reporting",
    "area": "report_review_support",
    "label": "Reports never discussed because no validation meeting occurs",
    "severity": "partial",
    "interventions": [
      {
        "id": "review_emr_reports_at_the__9e347a",
        "label": "Review EMR reports at the monthly performance meeting. Agree actions, write them down and check they were done.",
        "horizon": "minor",
        "costNGN": 20000
      }
    ]
  }
];

export const GAP_BY_ID: Record<string, GapDef> = Object.fromEntries(
  GAPS.map((g) => [g.id, g]),
);

/** Gaps for a domain selection. No domains ticked means every gap. */
export function gapsForDomains(domains: readonly string[]): GapDef[] {
  if (!domains.length) return GAPS;
  return GAPS.filter((g) => domains.includes(g.domain));
}

/**
 * The gap ids in scope under the Domain and Gap area filters together. **The
 * rule.**
 *
 * Every figure derived from gaps goes through here — the pane's headline, the
 * per-domain rows, the facility card, the list rows and the map's investment
 * fills. That is the point: they cannot disagree about what was selected.
 *
 * Both filters narrow, and a gap area narrows *which gaps are counted*, not
 * only which facilities are in scope. Selecting a domain's areas and selecting
 * the domain give identical figures, because every gap sits in exactly one area
 * and every area in exactly one domain.
 */
export function offeredGapIds(
  domains: readonly string[],
  gapAreas: readonly string[],
): Set<string> {
  const areas = gapAreas.length ? new Set(gapAreas) : null;
  const ids = new Set<string>();
  for (const g of GAPS) {
    if (domains.length && !domains.includes(g.domain)) continue;
    if (areas && !areas.has(g.area)) continue;
    ids.add(g.id);
  }
  return ids;
}

/** The conditions inside one area, worst-first — the order `GAPS` is already
 *  in, so this is a filter rather than a sort. */
export function gapsInArea(areaId: GapAreaId): GapDef[] {
  return GAPS.filter((g) => g.area === areaId);
}

/**
 * Whether an area can block deployment at all.
 *
 * The worst severity any of its conditions carries — so `blocking` means *some
 * facility here is stopped*, not that every one is. Only 3 of the 20 areas
 * qualify, all in Technical Infrastructure; see docs/GAP_TAXONOMY.md.
 */
export function gapAreaSeverity(areaId: GapAreaId): GapSeverity {
  return gapsInArea(areaId).some((g) => g.severity === 'blocking') ? 'blocking' : 'partial';
}

/** The areas a facility carries a gap in. At most one condition feeds each, so
 *  the length is how many of the 20 areas are a problem here. */
export function facilityGapAreas(gapIds: readonly string[]): GapAreaId[] {
  const seen = new Set<GapAreaId>();
  for (const id of gapIds) {
    const area = GAP_BY_ID[id]?.area;
    if (area) seen.add(area);
  }
  return GAP_AREAS.filter((a) => seen.has(a.id)).map((a) => a.id);
}

/** Does this facility carry a gap in any of these areas? The Gap area filter's
 *  own question — OR within the control, like every other multi-select. */
export function hasGapInAreas(gapIds: readonly string[], areas: readonly string[]): boolean {
  if (!areas.length) return true;
  return gapIds.some((id) => areas.includes(GAP_BY_ID[id]?.area ?? ''));
}

/**
 * What a gap costs.
 *
 * No facility argument: nothing in the source is quantity-scaled, so a gap
 * costs the same wherever it appears. Unpriced interventions are reported
 * separately rather than counted as zero, so a total never silently absorbs a
 * missing price.
 */
export function gapCostNGN(gap: GapDef): { costNGN: number; unpriced: number } {
  let costNGN = 0;
  let unpriced = 0;
  for (const iv of gap.interventions) {
    if (iv.costNGN === null) unpriced += 1;
    else costNGN += iv.costNGN;
  }
  return { costNGN, unpriced };
}

/** Band ranks, so a caller can order gap severity beside a readiness band. */
export const SEVERITY_BAND: Record<GapSeverity, Band> = {
  blocking: "not_ready",
  partial: "moderately_ready",
};

/** The four domains a facility is banded on. */
export const FACILITY_DOMAIN_IDS: FacilityThemeId[] = ["technical_infrastructure","workforce_capacity","workflow_transition","data_use_reporting"];
