/**
 * GENERATED by scripts/generate-dummy-data.mjs — do not edit.
 *
 * The gap dictionary, as the app sees it. The build-time source of truth is
 * `scripts/gap-catalogue.mjs`; this is the same table with the generator's
 * private fields — prevalence weights, exclusions — left behind, because a
 * running dashboard has no business knowing how often a gap was *drawn*.
 *
 * Emitted rather than fetched: every control that offers a gap needs the whole
 * list before it can render one, so a network round-trip would only buy a
 * spinner on a filter dropdown.
 */

import type {
  Band,
  FacilityThemeId,
  GapDomainId,
  GapSeverity,
  Horizon,
} from "./types";

export const HORIZONS: Horizon[] = ["immediate", "near_term", "long_term"];

export const HORIZON_LABEL: Record<Horizon, string> = {
  immediate: "Immediate",
  near_term: "Near-term",
  long_term: "Long-term",
};

/** The five domains. Two of them carry gaps that cost nothing to close, and one
 *  of those attaches to a state rather than a facility. */
export const GAP_DOMAINS = [
  {
    id: "technical_infrastructure",
    label: "Technical Infrastructure",
    level: "facility",
    costed: true,
  },
  {
    id: "workforce_capacity",
    label: "Workforce Capacity",
    level: "facility",
    costed: true,
  },
  {
    id: "workflow_transition",
    label: "Workflow & Transition",
    level: "facility",
    costed: true,
  },
  {
    id: "data_use_reporting",
    label: "Data Use & Reporting",
    level: "facility",
    costed: false,
  },
  {
    id: "leadership_governance",
    label: "Leadership & Governance",
    level: "state",
    costed: false,
  },
] as const;

export const GAP_DOMAIN_LABEL: Record<GapDomainId, string> = {
  technical_infrastructure: "Technical Infrastructure",
  workforce_capacity: "Workforce Capacity",
  workflow_transition: "Workflow & Transition",
  data_use_reporting: "Data Use & Reporting",
  leadership_governance: "Leadership & Governance",
};

export interface GapDef {
  id: string;
  domain: GapDomainId;
  subDomain: string;
  indicator: string;
  label: string;
  severity: GapSeverity;
  interventions: {
    id: string;
    label: string;
    horizon: Horizon;
    unitBasis: string;
    unitCostNGN: number;
  }[];
}

export const GAPS: GapDef[] = [
  {
    id: "grid_not_connected",
    domain: "technical_infrastructure",
    subDomain: "Power infrastructure",
    indicator: "National grid connection",
    label: "No national grid connection",
    severity: "partial",
    interventions: [
      {
        id: "grid_connection",
        label: "Grid connection",
        horizon: "long_term",
        unitCostNGN: 500000,
        unitBasis: "per_facility",
      },
    ],
  },
  {
    id: "backup_partial_solar",
    domain: "technical_infrastructure",
    subDomain: "Power infrastructure",
    indicator: "Backup functionality",
    label: "Solar backup only partially functional",
    severity: "partial",
    interventions: [
      {
        id: "solar_top_up",
        label: "Solar/battery top-up",
        horizon: "near_term",
        unitCostNGN: 1200000,
        unitBasis: "per_facility",
      },
    ],
  },
  {
    id: "backup_partial_generator",
    domain: "technical_infrastructure",
    subDomain: "Power infrastructure",
    indicator: "Backup functionality",
    label: "Generator backup only partially functional",
    severity: "partial",
    interventions: [
      {
        id: "generator_repair",
        label: "Generator repair",
        horizon: "near_term",
        unitCostNGN: 250000,
        unitBasis: "per_facility",
      },
      {
        id: "solar_pv_system",
        label: "Solar PV battery systems",
        horizon: "long_term",
        unitCostNGN: 3000000,
        unitBasis: "per_facility",
      },
    ],
  },
  {
    id: "backup_partial_inverter",
    domain: "technical_infrastructure",
    subDomain: "Power infrastructure",
    indicator: "Backup functionality",
    label: "Inverter backup only partially functional",
    severity: "partial",
    interventions: [
      {
        id: "inverter_repair",
        label: "Inverter repair",
        horizon: "near_term",
        unitCostNGN: 650000,
        unitBasis: "per_facility",
      },
    ],
  },
  {
    id: "backup_none",
    domain: "technical_infrastructure",
    subDomain: "Power infrastructure",
    indicator: "Backup functionality",
    label: "No functioning backup power",
    severity: "blocking",
    interventions: [
      {
        id: "power_tank",
        label: "Power tank",
        horizon: "near_term",
        unitCostNGN: 380000,
        unitBasis: "per_facility",
      },
      {
        id: "solar_pv_system",
        label: "Solar PV battery systems",
        horizon: "long_term",
        unitCostNGN: 3000000,
        unitBasis: "per_facility",
      },
    ],
  },
  {
    id: "wiring_inadequate",
    domain: "technical_infrastructure",
    subDomain: "Power infrastructure",
    indicator: "Electrical wiring status",
    label: "Electrical wiring absent or partially functional",
    severity: "partial",
    interventions: [
      {
        id: "basic_wiring",
        label: "Basic wiring and sockets",
        horizon: "immediate",
        unitCostNGN: 388000,
        unitBasis: "per_facility",
      },
    ],
  },
  {
    id: "no_internet",
    domain: "technical_infrastructure",
    subDomain: "Networking and connectivity",
    indicator: "Internet connectivity method",
    label: "No internet connection at the facility",
    severity: "blocking",
    interventions: [
      {
        id: "local_server",
        label: "Deploy local server within facility",
        horizon: "immediate",
        unitCostNGN: 650000,
        unitBasis: "per_facility",
      },
      {
        id: "nigcomsat",
        label: "Nigcomsat",
        horizon: "long_term",
        unitCostNGN: 3000000,
        unitBasis: "per_facility",
      },
    ],
  },
  {
    id: "internet_personal_device",
    domain: "technical_infrastructure",
    subDomain: "Networking and connectivity",
    indicator: "Internet connectivity method",
    label: "Internet only via personal hotspot or USB modem",
    severity: "partial",
    interventions: [
      {
        id: "emr_sim",
        label: "Dedicated EMR SIM card",
        horizon: "immediate",
        unitCostNGN: 1000,
        unitBasis: "per_facility",
      },
      {
        id: "router",
        label: "Router",
        horizon: "long_term",
        unitCostNGN: 40000,
        unitBasis: "per_device",
      },
    ],
  },
  {
    id: "internet_slow",
    domain: "technical_infrastructure",
    subDomain: "Networking and connectivity",
    indicator: "Internet speed",
    label: "Internet speed below 5 Mbps",
    severity: "partial",
    interventions: [
      {
        id: "local_server",
        label: "Deploy local server within facility",
        horizon: "immediate",
        unitCostNGN: 650000,
        unitBasis: "per_facility",
      },
    ],
  },
  {
    id: "devices_none",
    domain: "technical_infrastructure",
    subDomain: "Digital devices",
    indicator: "Computing devices",
    label: "No computing device at the facility",
    severity: "blocking",
    interventions: [
      {
        id: "tablets_minimum",
        label: "Minimum of 3 devices (tablets)",
        horizon: "near_term",
        unitCostNGN: 700000,
        unitBasis: "per_facility",
      },
      {
        id: "device_contract",
        label: "National contract to close the device-service point gap",
        horizon: "long_term",
        unitCostNGN: 600000,
        unitBasis: "per_facility",
      },
    ],
  },
  {
    id: "devices_below_service_points",
    domain: "technical_infrastructure",
    subDomain: "Digital devices",
    indicator: "Computing devices",
    label: "Fewer devices than documenting service points",
    severity: "partial",
    interventions: [
      {
        id: "device_contract",
        label: "National contract to close the device-service point gap",
        horizon: "near_term",
        unitCostNGN: 600000,
        unitBasis: "per_device",
      },
    ],
  },
  {
    id: "digital_competency",
    domain: "workforce_capacity",
    subDomain: "Core workforce",
    indicator: "Digital competency",
    label: "Staff lack basic digital competency",
    severity: "blocking",
    interventions: [
      {
        id: "digital_literacy",
        label: "Foundational digital literacy training through PFMOs",
        horizon: "immediate",
        unitCostNGN: 30000,
        unitBasis: "per_staff",
      },
    ],
  },
  {
    id: "focal_person",
    domain: "workforce_capacity",
    subDomain: "Core workforce",
    indicator: "EMR/Data focal person",
    label: "No EMR or data focal person",
    severity: "partial",
    interventions: [
      {
        id: "designate_focal_person",
        label:
          "Designate an EMR focal person (OIC where no Health Records Officer exists)",
        horizon: "immediate",
        unitCostNGN: 0,
        unitBasis: "per_facility",
      },
      {
        id: "recruit_hro",
        label:
          "Work with the SMOH to recruit full-time health records officers",
        horizon: "long_term",
        unitCostNGN: 1800000,
        unitBasis: "per_facility",
      },
    ],
  },
  {
    id: "emr_training",
    domain: "workforce_capacity",
    subDomain: "Workforce support",
    indicator: "Training",
    label: "Staff not trained on the EMR",
    severity: "partial",
    interventions: [
      {
        id: "emr_training",
        label: "EMR training of a facility staff to be cascaded to other staff",
        horizon: "near_term",
        unitCostNGN: 30000,
        unitBasis: "per_staff",
      },
      {
        id: "refresher_modules",
        label:
          "Develop EMR refresher modules via the NPHCDA e-learning platform",
        horizon: "long_term",
        unitCostNGN: 100000,
        unitBasis: "per_facility",
      },
    ],
  },
  {
    id: "technical_support",
    domain: "workforce_capacity",
    subDomain: "Workforce support",
    indicator: "Technical support",
    label: "No technical support route for the facility",
    severity: "partial",
    interventions: [
      {
        id: "support_desk",
        label: "Attach the facility to the LGA technical support desk",
        horizon: "near_term",
        unitCostNGN: 95000,
        unitBasis: "per_facility",
      },
    ],
  },
  {
    id: "duplicate_entry",
    domain: "workflow_transition",
    subDomain: "Workflow and service points",
    indicator: "Duplicate entry",
    label: "The same record is written more than once",
    severity: "partial",
    interventions: [
      {
        id: "workflow_sops",
        label: "Develop standardized workflow SOPs",
        horizon: "immediate",
        unitCostNGN: 0,
        unitBasis: "per_facility",
      },
      {
        id: "configure_workflows",
        label:
          "Configure EMR workflows to reflect documented service point configurations",
        horizon: "near_term",
        unitCostNGN: 120000,
        unitBasis: "per_facility",
      },
    ],
  },
  {
    id: "workflow_bottleneck",
    domain: "workflow_transition",
    subDomain: "Workflow and service points",
    indicator: "Workflow bottleneck",
    label: "A service point holds up the rest of the flow",
    severity: "partial",
    interventions: [
      {
        id: "documentation_responsibilities",
        label:
          "Define documentation responsibilities and configure user accounts",
        horizon: "near_term",
        unitCostNGN: 0,
        unitBasis: "per_facility",
      },
    ],
  },
  {
    id: "physical_service_point",
    domain: "workflow_transition",
    subDomain: "Workflow and service points",
    indicator: "Physical service point",
    label: "Service points lack the furniture and power to document at",
    severity: "blocking",
    interventions: [
      {
        id: "procure_desks",
        label: "Procure desks",
        horizon: "near_term",
        unitCostNGN: 35000,
        unitBasis: "per_service_point",
      },
      {
        id: "procure_chairs",
        label: "Procure chairs",
        horizon: "near_term",
        unitCostNGN: 25892,
        unitBasis: "per_service_point",
      },
      {
        id: "procure_sockets",
        label: "Procure electric sockets",
        horizon: "immediate",
        unitCostNGN: 15000,
        unitBasis: "per_service_point",
      },
      {
        id: "procure_fan",
        label: "Procure electric fan",
        horizon: "near_term",
        unitCostNGN: 96000,
        unitBasis: "per_service_point",
      },
      {
        id: "procure_lockable_door",
        label: "Procure lockable door",
        horizon: "long_term",
        unitCostNGN: 100000,
        unitBasis: "per_service_point",
      },
    ],
  },
  {
    id: "staff_willingness",
    domain: "workflow_transition",
    subDomain: "Transition support",
    indicator: "Staff willingness",
    label: "Staff need support to move off paper",
    severity: "partial",
    interventions: [
      {
        id: "change_champions",
        label: "Establish facility-level change champions and routine feedback",
        horizon: "near_term",
        unitCostNGN: 0,
        unitBasis: "per_facility",
      },
    ],
  },
  {
    id: "records_digitisation",
    domain: "workflow_transition",
    subDomain: "Transition support",
    indicator: "Records digitisation",
    label: "Historical paper records still to be digitised",
    severity: "partial",
    interventions: [
      {
        id: "transition_support",
        label:
          "Provide transition support including digitisation of historical records",
        horizon: "long_term",
        unitCostNGN: 240000,
        unitBasis: "per_facility",
      },
    ],
  },
  {
    id: "routine_data_use",
    domain: "data_use_reporting",
    subDomain: "Data-use core",
    indicator: "Routine data use",
    label: "Service data is not used in routine decisions",
    severity: "blocking",
    interventions: [
      {
        id: "shared_template",
        label: "Establish shared spreadsheet or basic template",
        horizon: "immediate",
        unitCostNGN: 0,
        unitBasis: "per_facility",
      },
    ],
  },
  {
    id: "data_validation",
    domain: "data_use_reporting",
    subDomain: "Data-use core",
    indicator: "Data validation",
    label: "No validation step before figures are reported",
    severity: "partial",
    interventions: [
      {
        id: "quality_checklist",
        label: "Issue a minimum data-quality checklist",
        horizon: "immediate",
        unitCostNGN: 0,
        unitBasis: "per_facility",
      },
    ],
  },
  {
    id: "report_review",
    domain: "data_use_reporting",
    subDomain: "Reporting support",
    indicator: "Report review",
    label: "Reports are submitted but never discussed",
    severity: "partial",
    interventions: [
      {
        id: "report_discussion",
        label:
          "Use the existing report-discussion routine as the entry point for EMR reports",
        horizon: "near_term",
        unitCostNGN: 0,
        unitBasis: "per_facility",
      },
    ],
  },
  {
    id: "no_budget_line",
    domain: "leadership_governance",
    subDomain: "Institutional readiness",
    indicator: "Financing and budget commitment",
    label: "No dedicated budget line for digital health",
    severity: "blocking",
    interventions: [
      {
        id: "budget_memo",
        label:
          "Issue a memo urging states to allocate a digital health budget line",
        horizon: "immediate",
        unitCostNGN: 0,
        unitBasis: "per_facility",
      },
    ],
  },
  {
    id: "no_emr_oversight",
    domain: "leadership_governance",
    subDomain: "Institutional readiness",
    indicator: "EMR oversight",
    label: "No governance body with EMR oversight",
    severity: "partial",
    interventions: [
      {
        id: "expand_twg",
        label:
          "Expand the mandate of existing M&E and Digital Health TWGs to include EMR",
        horizon: "immediate",
        unitCostNGN: 0,
        unitBasis: "per_facility",
      },
    ],
  },
  {
    id: "no_digital_strategy",
    domain: "leadership_governance",
    subDomain: "Digital health use",
    indicator: "Digital health strategy",
    label: "No digital health strategy",
    severity: "blocking",
    interventions: [
      {
        id: "digital_strategy",
        label: "Develop a digital health strategy",
        horizon: "near_term",
        unitCostNGN: 0,
        unitBasis: "per_facility",
      },
    ],
  },
  {
    id: "no_state_engagement",
    domain: "leadership_governance",
    subDomain: "Digital health use",
    indicator: "Stakeholder engagement",
    label: "State not engaged as a co-decision-maker in EMR planning",
    severity: "partial",
    interventions: [
      {
        id: "engage_states",
        label: "Engage states as co-decision-makers and provide backend access",
        horizon: "near_term",
        unitCostNGN: 0,
        unitBasis: "per_facility",
      },
    ],
  },
  {
    id: "no_interoperability",
    domain: "leadership_governance",
    subDomain: "Sustainability and scale",
    indicator: "Interoperability",
    label: "Existing systems are not interoperable with the EMR",
    severity: "partial",
    interventions: [
      {
        id: "interoperable_emr",
        label:
          "Ensure EMRs are interoperable with other digital health systems",
        horizon: "long_term",
        unitCostNGN: 0,
        unitBasis: "per_facility",
      },
    ],
  },
  {
    id: "no_continuous_training",
    domain: "leadership_governance",
    subDomain: "Sustainability and scale",
    indicator: "Capacity building",
    label: "No route to continuous EMR training",
    severity: "partial",
    interventions: [
      {
        id: "elearning_platform",
        label:
          "Leverage the national e-learning platform for continuous training",
        horizon: "long_term",
        unitCostNGN: 0,
        unitBasis: "per_facility",
      },
    ],
  },
];

export const GAP_BY_ID: Record<string, GapDef> = Object.fromEntries(
  GAPS.map((g) => [g.id, g]),
);

/** Gaps for a domain selection. No domains ticked means every facility-level
 *  gap, which is what the Gap control offers when Domain is left alone. */
export function gapsForDomains(domains: readonly string[]): GapDef[] {
  const facilityLevel = GAPS.filter(
    (g) => g.domain !== "leadership_governance" || domains.includes(g.domain),
  );
  if (!domains.length)
    return facilityLevel.filter((g) => g.domain !== "leadership_governance");
  return GAPS.filter((g) => domains.includes(g.domain));
}

/** A gap's cost for one facility-shaped thing, at the quantities it implies. */
export function gapCostNGN(
  gap: GapDef,
  size: { servicePoints: number; staffCount: number; deviceShortfall: number },
): number {
  return gap.interventions.reduce((sum, iv) => {
    const q =
      iv.unitBasis === "per_service_point"
        ? size.servicePoints
        : iv.unitBasis === "per_staff"
          ? size.staffCount
          : iv.unitBasis === "per_device"
            ? Math.max(1, size.deviceShortfall)
            : 1;
    return sum + q * iv.unitCostNGN;
  }, 0);
}

/** Band ranks, so a caller can order gap severity beside a readiness band. */
export const SEVERITY_BAND: Record<GapSeverity, Band> = {
  blocking: "not_ready",
  partial: "moderately_ready",
};

/** The four domains a facility is banded on. Leadership is a state's. */
export const FACILITY_DOMAIN_IDS: FacilityThemeId[] = [
  "technical_infrastructure",
  "workforce_capacity",
  "workflow_transition",
  "data_use_reporting",
];
