/**
 * GENERATED by scripts/ingest-assessment.mjs — do not edit.
 *
 * The national EMR-deployment readiness split, available synchronously so the
 * landing page can paint before `DataProvider` has fetched anything.
 *
 * The one overall reading the dataset carries — the same figures every page
 * behind the front door is working from.
 */

import type { Band } from './types';

export const NATIONAL_DEPLOYMENT_SPLIT: Record<Band, number> = {"not_ready":744,"moderately_ready":1892,"ready":170};

/** Facilities carrying a band — the denominator every share on the landing
 *  page is taken over. Every assessed facility carries one, so this is simply
 *  the survey size. */
export const NATIONAL_TOTAL = 2806;

/**
 * Facility actions the source records and does not price — routine device
 * maintenance, naming an EMR focal person, and the lockable-door checks the
 * sheet leaves "before costing".
 *
 * Generated rather than written into the footer as an adjective: the front
 * door states that its costs are incomplete, and how incomplete they are must
 * not be able to drift from the dataset saying so.
 */
export const NATIONAL_UNPRICED_ACTIONS: number = 4654;
