/**
 * GENERATED by scripts/ingest-assessment.mjs — do not edit.
 *
 * The national EMR-deployment readiness split, available synchronously so the
 * landing page can paint before `DataProvider` has fetched anything.
 *
 * The one overall reading the dataset carries — the same figures every page
 * behind the front door is working from.
 */

import type { Band } from './types';

export const NATIONAL_DEPLOYMENT_SPLIT: Record<Band, number> = {"not_ready":744,"moderately_ready":1892,"ready":170};

/** Facilities carrying a band — the denominator every share on the landing
 *  page is taken over. Every assessed facility carries one, so this is simply
 *  the survey size. */
export const NATIONAL_TOTAL = 2806;
