/**
 * GENERATED by scripts/ingest-assessment.mjs — do not edit.
 *
 * The national EMR-deployment readiness split, available synchronously so the
 * landing page can paint before `DataProvider` has fetched anything.
 *
 * Deployment, not use: this dashboard's question is what it takes to *deploy*
 * an EMR, and a front door that led with the use split reported a different
 * Ready count from every page behind it.
 */

import type { Band } from './types';

export const NATIONAL_DEPLOYMENT_SPLIT: Record<Band, number> = {"not_ready":1340,"moderately_ready":842,"ready":624};

/** Facilities carrying a band — the denominator every share on the landing
 *  page is taken over. Every assessed facility carries both overall bands, so
 *  this is simply the survey size. */
export const NATIONAL_TOTAL = 2806;
